# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-23 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.TextField(default=b'')),
                ('mobile', models.CharField(max_length=15)),
                ('image_url', models.URLField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default=b'', max_length=20)),
                ('current_price', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('short_name', models.CharField(default=b'', max_length=20)),
                ('long_name', models.CharField(default=b'', max_length=50)),
                ('previous_price', models.IntegerField(default=0)),
                ('soldBy', models.CharField(default=b'Zamrine', max_length=50)),
                ('product_type', models.CharField(default=b'shop', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zamrine_web_application.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[(b'S', b'Small'), (b'M', b'Medium'), (b'L', b'Large'), (b'XL', b'ExtraLarge')], max_length=2)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='zamrine_web_application.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('image_url', models.URLField(null=True)),
                ('message', models.TextField(null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zamrine_web_application.Product')),
            ],
        ),
    ]
