# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 08:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_column='category', max_length=20)),
                ('currentPrice', models.IntegerField(db_column='current_price')),
                ('description', models.CharField(db_column='description', max_length=200)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), db_column='images', size=None)),
                ('longName', models.CharField(db_column='long_name', max_length=50)),
                ('previousPrice', models.IntegerField(blank=True, db_column='previous_price')),
                ('relatedProducts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), db_column='related_products', size=None)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), db_column='sizes', size=None)),
                ('soldBy', models.CharField(db_column='sold_by', max_length=50)),
                ('type', models.CharField(db_column='type', max_length=10)),
            ],
        ),
    ]
