# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='relatedProducts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
