# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0003_auto_20200722_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='previous_price',
        ),
    ]
