# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0006_auto_20200722_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
