# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0007_auto_20200722_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=3),
        ),
    ]
