# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0012_auto_20200722_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(null=True, to='zamrine_web_application.ProductImages'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(null=True, to='zamrine_web_application.ProductSizes'),
        ),
    ]
