# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0017_auto_20200722_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_url', to='zamrine_web_application.Product'),
        ),
        migrations.AddField(
            model_name='productsizes',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='zamrine_web_application.Product'),
        ),
    ]
