# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0018_auto_20200722_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zamrine_web_application.Product'),
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='zamrine_web_application.Product'),
        ),
    ]
