# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0019_auto_20200722_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('image_url', models.URLField(null=True)),
                ('message', models.TextField(null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('rating', models.DecimalField(decimal_places=3, max_digits=5)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='zamrine_web_application.Product')),
            ],
        ),
    ]
