# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-22 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0023_product_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_name',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default=b'shop', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_name',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='soldBy',
            field=models.CharField(default=b'Zamrine', max_length=50),
        ),
    ]
