# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zamrine_web_application', '0025_auto_20200722_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zamrine_web_application.Product'),
        ),
    ]
